language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install nose coverage
script:
  - make ci
after_success:
  - |
        pip install coveralls
        coveralls

notifications:
  email:
    on_failure: change
    on_success: never
