language: python
cache: pip
python:
  - 3.6
install:
  - |
        pip install nose nose-tap coverage flake8 pylint
        pip install -r requirements.txt

        cat > ~/.tcms.conf << __EOF__
[tcms]
url = https://tcms.kiwitcms.org/xml-rpc/
username = kiwitcms-bot
password = $TCMS_PASSWORD
__EOF__
        cat ~/.tcms.conf

script:
  - make ci
after_success:
  - |
        pip install coveralls
        coveralls

notifications:
  email:
    on_failure: change
    on_success: never
