sudo: required
language: python
cache: pip
python:
  - 3.6
env:
  - MAKE=ci
  - MAKE=tap
install:
  - pip install -r devel.txt
  - |
        echo "[tcms]" > ~/.tcms.conf
        echo "url = https://tcms.kiwitcms.org/xml-rpc/" >> ~/.tcms.conf
        echo "username = kiwitcms-bot" >> ~/.tcms.conf
        echo "password = $TCMS_PASSWORD" >> ~/.tcms.conf

        sudo cp .ssl/*.pem /usr/lib/ssl/certs/
        sudo update-ca-certificates --fresh

script:
  - make $MAKE

after_success:
  - |
        pip install coveralls
        coveralls

notifications:
  email:
    on_failure: change
    on_success: never
